on:
  workflow_dispatch:
  schedule:
  - cron: "* */3 * * *"

jobs:
  get-trivy-dbs:
    runs-on: ubuntu-latest
    env:
      ORG_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: setup-oras
      uses: oras-project/setup-oras@v1.2.1

    - name: login to ghcr
      run: oras login -u ${{ github.actor }} -p "${{ secrets.GH_TOKEN }}" ghcr.io
    - name: copy java database
      run: oras cp ghcr.io/aquasecurity/trivy-java-db:1 ghcr.io/lapayne/sharedassets/trivy-java-db:1 
    - name: copy DB
      run: oras cp ghcr.io/aquasecurity/trivy-db:2 ghcr.io/lapayne/sharedassets/trivy-db:2
    
